spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/clearSolutionsAssignment?createDatabaseIfNotExist'
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: frost1234!
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master-dev.xml'
    contexts: dev
  web:
    locale: en_EN
    locale-resolver: fixed
jsondoc:
  version: '1.0'
  basePath: 'http://localhost:8080'
  packages[0]: 'com.example.assignment.web.controller'
  packages[1]: 'com.example.assignment.domain.repository.param'
  packages[2]: 'com.example.assignment.core.dto'
  # optional configuration
  playgroundEnabled: 'true'
  displayMethodAs: 'URI'

